[package]
name = "day5"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.86"
itertools = "0.13.0"
nom = "7.1.3"
rayon = "1.10.0"

[features]
alloc = []
